name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull repo
      uses: actions/checkout@v1

    - name: build and push image
      run: |
        docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_PASSWORD }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/kode-collektiv/frontend/frontend:latest
        docker push docker.pkg.github.com/kode-collektiv/frontend/frontend:latest
        
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        passphrase: ${{ secrets.HOST_PASSPHRASE }}

      env:
        CI: true
